# rubocop todo

Lint/UselessAssignment:
  Exclude:
    - 'recipes/slave.rb'

# Configuration parameters: Methods.
# Methods: {"reduce"=>["a", "e"]}, {"inject"=>["a", "e"]}
Style/SingleLineBlockParams:
  Exclude:
    - 'recipes/master.rb'
